apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appchart.fullname" . }}
  labels:
    {{- include "appchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "appchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: {{ .Values.initContainer.image }}
          restartPolicy: never
          imagePullPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image1.repository }}:{{ .Values.image1.tag}}"
          imagePullPolicy: {{ .Values.image1.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.serviceApp.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-search
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image2.repository }}:{{ .Values.image2.tag}}"
          imagePullPolicy: {{ .Values.image2.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.serviceSearch.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
              # initialDelaySeconds: 5
              # timeoutSeconds: 2
              # periodSeconds: 5
              # successThreshold: 1
              # failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
              # initialDelaySeconds: 5
              # timeoutSeconds: 2
              # periodSeconds: 5
              # successThreshold: 1
              # failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
