apiVersion: v1
kind: Service
metadata:
  name: {{ include "appchart.fullname" . }}
  labels:
    {{- include "appchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceApp.type }}
  ports:
    - port: {{ .Values.serviceApp.port }}
      targetPort: http
      protocol: TCP
      name: app
    - port: {{ .Values.serviceSearch.port }}
      targetPort: http
      protocol: TCP
      name: search
  selector:
    {{- include "appchart.selectorLabels" . | nindent 4 }}
